stateDiagram-v2
[*] --> entry:一覧画面
entry : /

entry --> taskCreate:新規登録フォーム
entry --> taskDetail:詳細表示

taskCreate : /create
taskDetail : /tasks/id
taskEdit   : /edit/id

entry      --> taskDetail:詳細リンク
taskDetail --> entry:一覧へ戻る
taskDetail --> taskEdit:編集フォーム
taskEdit   --> taskDetail:更新後の詳細
taskEdit   --> entry:一覧へ戻る
